name: Build & Deploy to ArgoCD/Kind

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: cirobessa/spina-challenge
      IMAGE_TAG: latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:$IMAGE_TAG

  notify-argocd:
    name: Trigger ArgoCD Sync (Local Kind)
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Port-forward ArgoCD API locally (optional)
      run: |
        echo "ArgoCD API is currently NOT reachable from runner"
        # kubectl port-forward svc/argocd-server -n argocd 8080:443 &

    - name: Trigger ArgoCD Sync
      run: |
        echo "ArgoCD API is currently NOT reachable from runner"
        #curl -X POST https://your-argocd-api.local/api/v1/applications/spina/sync \
        #  -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}"
